# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from PyQt5.QtCore import Qt


class Ui_EditReport(QWidget):
    def setupUi(self, EditReport):
        EditReport.setObjectName("EditReport")
        self.setWindowFlags(self.windowFlags() & ~Qt.WindowMinMaxButtonsHint)
        self.setFixedSize(649, 443)
        self.centralwidget = QtWidgets.QWidget(EditReport)
        self.centralwidget.setStyleSheet("background-color: rgb(222, 248, 255)")
        self.centralwidget.setObjectName("centralwidget")
        self.txtReport = QtWidgets.QTextEdit(self.centralwidget)
        self.txtReport.setGeometry(QtCore.QRect(20, 20, 611, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtReport.setFont(font)
        self.txtReport.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtReport.setObjectName("txtReport")
        self.btClear = QtWidgets.QPushButton(self.centralwidget)
        self.btClear.setGeometry(QtCore.QRect(30, 400, 81, 31))
        self.btClear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btClear.setObjectName("btClear")
        self.btSave = QtWidgets.QPushButton(self.centralwidget)
        self.btSave.setGeometry(QtCore.QRect(540, 400, 81, 31))
        self.btSave.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btSave.setObjectName("btSave")
        EditReport.setCentralWidget(self.centralwidget)

        self.retranslateUi(EditReport)
        QtCore.QMetaObject.connectSlotsByName(EditReport)

    def retranslateUi(self, EditReport):
        _translate = QtCore.QCoreApplication.translate
        EditReport.setWindowTitle(_translate("EditReport", "Radyoloji Raporunu Düzenle"))
        self.btClear.setText(_translate("EditReport", "Temizle"))
        self.btSave.setText(_translate("EditReport", "Kaydet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditReport = QtWidgets.QMainWindow()
    ui = Ui_EditReport()
    ui.setupUi(EditReport)
    EditReport.show()
    sys.exit(app.exec_())
