# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newDicomTags.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMenu, QAction


class Ui_MainWindow2(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 621)
        
        self.saveMenu = QMenu()

        # Menü öğeleri ekle
        self.saveAsTxt = QAction("Etiketleri Kaydet(.txt)")
        self.saveAsCsv = QAction("Etiketleri Kaydet(.csv)")
        self.saveAsXlsx = QAction("Etiketleri Kaydet(.xlsx)")
        self.saveAsPdf = QAction("Etiketleri Kaydet(.pdf)")

        # Menü öğelerini menüye ekle
        self.saveMenu.addAction(self.saveAsTxt)
        self.saveMenu.addAction(self.saveAsCsv)
        self.saveMenu.addAction(self.saveAsXlsx)
        self.saveMenu.addAction(self.saveAsPdf)

        self.setWindowFlags(self.windowFlags() & ~Qt.WindowMinMaxButtonsHint)
        self.setFixedSize(809, 621)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: rgb(207, 255, 234);")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 771, 531))
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 10, 221, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btSave = QtWidgets.QPushButton(self.centralwidget)
        self.btSave.setGeometry(QtCore.QRect(20, 580, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.btSave.setFont(font)
        self.btSave.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btSave.setObjectName("btSave")
        self.lblHeader = QtWidgets.QLabel(self.centralwidget)
        self.lblHeader.setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblHeader.setFont(font)
        self.lblHeader.setObjectName("lblHeader")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DICOM Etiketleri"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Value"))
        self.btSave.setText(_translate("MainWindow", "Farklı Kaydet"))
        self.lblHeader.setText(_translate("MainWindow", "Arama Yap :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
